filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
user.name=wayne
user.email=106659888+obstwayne@users.noreply.github.com
gpg.program=/.codespaces/bin/gh-gpgsign
init.defaultbranch=main
credential.helper=/.codespaces/bin/gitcredential_github.sh
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/obstwayne/future-project-just-me.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
